"""Generate Nextflow DSL2 scripts from PipelineDefinition."""

from bioforge.pipeline_engine.dsl import PipelineDefinition
from bioforge.pipeline_engine.graph import PipelineGraph


class NextflowBridge:
    """Convert BioForge pipelines to Nextflow DSL2 scripts."""

    def generate_script(self, definition: PipelineDefinition) -> str:
        """Convert a PipelineDefinition to a Nextflow DSL2 script."""
        graph = PipelineGraph(definition.steps)
        order = graph.topological_order()

        lines = [
            "#!/usr/bin/env nextflow",
            "nextflow.enable.dsl=2",
            "",
            f"// Pipeline: {definition.name}",
            f"// {definition.description}",
            "",
        ]

        # Generate process definitions
        for step_name in order:
            step = graph.steps[step_name]
            container = step.container or "ubuntu:latest"
            lines.extend([
                f"process {step_name} {{",
                f"    container '{container}'",
                "",
                "    input:",
            ])

            for port in step.inputs:
                lines.append(f"    path {port}")

            lines.extend([
                "",
                "    output:",
                f"    path 'output/*', emit: result",
                "",
                "    script:",
                '    """',
                f"    echo 'Running {step.step_type}'",
                f"    // TODO: implement {step.step_type} command",
                '    """',
                "}",
                "",
            ])

        # Generate workflow
        lines.extend([
            "workflow {",
            f"    // Execution order: {' -> '.join(order)}",
        ])

        for step_name in order:
            step = graph.steps[step_name]
            input_args = []
            for port, ref in step.inputs.items():
                src_step = ref.split(".")[0]
                input_args.append(f"{src_step}.out.result")
            if input_args:
                lines.append(f"    {step_name}({', '.join(input_args)})")
            else:
                lines.append(f"    {step_name}(Channel.empty())")

        lines.extend(["}", ""])

        return "\n".join(lines)

    def generate_config(self, definition: PipelineDefinition) -> str:
        """Generate a nextflow.config for the pipeline."""
        return "\n".join([
            "// Auto-generated by BioForge",
            f"// Pipeline: {definition.name}",
            "",
            "docker.enabled = true",
            "",
            "process {",
            "    cpus = 2",
            "    memory = '4 GB'",
            "}",
            "",
        ])
